// react/src/App.tsx
import * as React from 'react';
import './App.css';
import CountersList from './components/counters-list.component';

var appStyle = {
  textAlign: 'center'
};

class App extends React.Component<{}, {}> {
  render() {
    return (
      <div>
        <h1 style={appStyle}>Two Counters</h1>
        <CountersList />
      </div>
    );
  }
}

export default App;

// angular/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'Two Counters';
}

<h1 style="text-align:center">{{title}}</h1>
<app-counters-list></app-counters-list>
